### ISSUE TITLE
Id is used instead of positiveInt

### ISSUE THREAD

**Issue by akdu12** [MayJuun/fhir#12]
Hello,
Thank you for sharing these awesome packages.
I'm currently using them as a part of a flutter project and came across some issues regarding serialization. 
looking at the implementation [https://github.com/akdu12/fhir/blob/main/fhir/lib/stu3/resource_types/financial/general/general.dart](url)  `careTeamLinkId `, `procedureLinkId `, `diagnosisLinkId ` and `informationLinkId `are considered as a list of id while they should be a positiveInt [http://hl7.org/fhir/STU3/explanationofbenefit.html](doc)

**Comment by akdu12** [comment]
#14

**Comment by Dokotela** [comment]
Thanks for the PR!
