### ISSUE TITLE
Meta information lost on Resource.updateVersion

### ISSUE THREAD

**Issue by vsaase** [MayJuun/fhir#50]
https://github.com/MayJuun/fhir/blob/291559d2b9ee9e0f9607816b9aeeed82791fc2f8/fhir/lib/r4/resource/resource_new_version.dart#L11

Hi,
first thanks for the library, helped me a lot already.
In the above referenced line a new Meta instance is returned. This however ignores other fields that may be set in oldMeta, such as the profile. Could this be fixed with a conditional `oldMeta.copyWith` ? 
I would send a pull request, but I am not sure if you generate this code from somewhere else. I see all this duplications between dstu2, stu3, r4 and r5.

**Comment by Dokotela** [comment]
Fair, it's a lot of code to keep up with. Shouldn't be a problem with updating the meta using copyWith, I'll let you know when it's available.

**Comment by Dokotela** [comment]
Looks good, thanks!
