### ISSUE TITLE
Crash on Flutter versions > 3.7.0 when parsing FhirDateTime

### ISSUE THREAD

**Issue by vsaase** [MayJuun/fhir#55]
Just for reference, I opened a bug report here: flutter/flutter#121270
There seems to be a bug in the RegExp implementation introduced in 3.7.1

**Comment by Dokotela** [comment]
Awesome! Thanks for the update and for the feedback (I rarely get any, so it's hard to know if the packages are functioning as they should).

**Comment by AliakseiT** [comment]
~Does anyone have a success with 3.7.7 and this crash? It is fixed as per change log, but it is still there for me.~ Confirmed with 3.7.7

**Comment by Dokotela** [comment]
This is true for both iOS & Android? Do you have any examples you can post? I'd like to try and play around with it to see if maybe we can find a workaround if it's a Flutter issue.

**Comment by vsaase** [comment]
It is fixed in Flutter stable now

**Comment by Dokotela** [comment]
Perfect. In that case I'll close this. Thanks!
